name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'The number of milliseconds to wait before the action starts. '
    required: true
    default: '1000'
  slack_enabled:
    description: 'Enable Slack notifications'
    required: false
    default: 'false'
  slack_channel_id:
    description: 'The Slack channel ID to send notifications to'
  slack_access_token:
    description:
      'The Slack access token that has the necessary permissions to send
      messages to the channel'
  locale:
    description: 'The locale to use for the action'
    required: false
    default: 'en-us'
  member_id_list_to_mention:
    description:
      'A list of member IDs to mention in the Slack message, comma separated'
  api_documentation_url:
    description: 'The URL to the API documentation'
    required: false
  openapi_file_path:
    description: 'The path to the OpenAPI file'
    required: false
    default: 'openapi.json'
  head_commit_message:
    description: 'The message of the head commit'
  head_commit_sha:
    description: 'The SHA of the head commit'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'
  result:
    description: 'The result of the Typescript test'

runs:
  using: node20
  main: dist/index.js
